const prefix = 'UPLOAD_PLAN';
const type = 'LISTENER';

export default {
  VALIDATE_PLAN_DATA_REQUEST: `${type}:${prefix}_VALIDATE_PLAN_DATA_REQUEST`,
  UPLOAD_PLAN_DATA_REQUEST: `${type}:${prefix}_UPLOAD_PLAN_DATA_REQUEST`,
  SET_PLAN_CRITERIA_REQUEST: `${type}:${prefix}_SET_PLAN_CRITERIA_REQUEST`,
  RENDER_UPLOAD_TABLE: `${type}:${prefix}_RENDER_UPLOAD_TABLE`,
  CHECK_UPLOADED_PLANS: `${type}:${prefix}_CHECK_UPLOADED_PLANS`,
};
