const prefix = 'BUILDING_BLOCK';
const type = 'WORKER';

export default  {
  GET_BUILDING_BLOCKS_LIST_DATA_REQUEST: `${type}:${prefix}_GET_BUILDING_BLOCKS_LIST_DATA_REQUEST`,
  UPDATE_BUILDING_BLOCKS_LIST_DATA_REQUEST: `${type}:${prefix}_UPDATE_BUILDING_BLOCKS_LIST_DATA_REQUEST`,
  SET_BUILDING_BLOCKS_FILTER_REQUEST: `${type}:${prefix}_SET_BUILDING_BLOCKS_FILTER__REQUEST`,
  SET_STOP_LOADING: `${type}:${prefix}SET_STOP_LOADING`,
  SET_START_LOADING: `${type}:${prefix}SET_START_LOADING`,
};

