const prefix = 'PLAN';
const type = 'WORKER';

export default  {
  GET_CURRENT_PLAN_DATA_REQUEST: `${type}:${prefix}_GET_CURRENT_PLAN_DATA_REQUEST`,
  SET_PLAN_CRITERIA_REQUEST_DATE: `${type}:${prefix}_SET_PLAN_CRITERIA_REQUEST_DATE`,
  SET_CURRENT_PLAN_FILTER_REQUEST: `${type}:${prefix}_SET_CURRENT_PLAN_FILTER_REQUEST`,
  SET_CURRENT_PLAN_ERROR_MESSAGE: `${type}:${prefix}_SET_CURRENT_PLAN_ERROR_MESSAGE`,
  SET_CURRENT_BUILDING_BLOCK_REQUEST: `${type}:${prefix}_SET_CURRENT_BUILDING_BLOCK_REQUEST`,
  SET_CURRENT_PLAN_STOP_LOADING: `${type}:${prefix}_SET_CURRENT_PLAN_STOP_LOADING`,
  SET_CURRENT_PLAN_START_LOADING: `${type}:${prefix}_SET_CURRENT_PLAN_START_LOADING`,
  SET_CURRENT_PLAN_NEW_VALUE_REQUEST: `${type}:${prefix}_SET_CURRENT_PLAN_NEW_VALUE_REQUEST`,
};

