const prefix = 'PLAN_PIVOT';
const type = 'WORKER';

export default  {
  GET_CURRENT_PLAN_DATA_REQUEST: `${type}:${prefix}_GET_CURRENT_PLAN_DATA_REQUEST`,
  SET_SINGLE_PIVOT_TO_CURRENT_PLAN: `${type}:${prefix}_SET_SINGLE_PIVOT_TO_CURRENT_PLAN`,
  REMOVE_SINGLE_PIVOT_FROM_CURRENT_PLAN: `${type}:${prefix}_REMOVE_SINGLE_PIVOT_FROM_CURRENT_PLAN`,
  SET_NEW_PIVOTS_ORDER: `${type}:${prefix}_SET_NEW_PIVOTS_ORDER`,
  SET_ALL_PIVOTS_TO_CURRENT_PLAN: `${type}:${prefix}_SET_ALL_PIVOTS_TO_CURRENT_PLAN:`,
  GET_ALL_PIVOT_DATA_TAB_LIST: `${type}:${prefix}_GET_ALL_PIVOT_DATA_TAB_LIST:`,
  SET_ACTIVE_PIVOT_ID: `${type}:${prefix}_SET_ACTIVE_PIVOT_ID:`,
  SET_STOP_LOADING: `${type}:${prefix}_SET_STOP_LOADING`,
  SET_START_LOADING: `${type}:${prefix}_SET_START_LOADING`,
};

