const prefix = 'UPLOAD_PLAN';
const type = 'WORKER';

export default  {
  SET_PLAN_CRITERIA_REQUEST_COUNTRY: `${type}:${prefix}_SET_PLAN_CRITERIA_REQUEST_COUNTRY`,
  SET_PLAN_CRITERIA_REQUEST_DATE: `${type}:${prefix}_SET_PLAN_CRITERIA_REQUEST_DATE`,
  SET_BASIC_BUILDING_BLOCKS: `${type}:${prefix}_SET_BASIC_BUILDING_BLOCKS`,
  SET_COUNTRY_CLUSTERS_LIST: `${type}:${prefix}_SET_COUNTRY_CLUSTERS_LIST`,
  SET_SMALL_CATEGORIES_LIST: `${type}:${prefix}_SET_SMALL_CATEGORIES_LIST`,
  GET_ALREADY_UPLOADED_PLAN: `${type}:${prefix}_GET_ALREADY_UPLOADED_PLAN`,
  UPLOAD_PLAN_REQUEST: `${type}:${prefix}_UPLOAD_PLAN_REQUEST`,
  UPLOAD_PLAN_SUCCESS: `${type}:${prefix}_UPLOAD_PLAN_SUCCESS`,
  UPLOAD_PLAN_ERROR: `${type}:${prefix}_UPLOAD_PLAN_ERROR`,
  SET_UPLOAD_PLAN_QUERY_REQUEST: `${type}:${prefix}_SET_UPLOAD_PLAN_QUERY_REQUEST`,


};

