const prefix = 'USERS';
const type = 'WORKER';

export default  {
  GET_USERS_LIST_REQUEST: `${type}:${prefix}_GET_USERS_LIST_REQUEST`,
  GET_USERS_LIST_SUCCESS: `${type}:${prefix}_GET_USERS_LIST_SUCCESS`,
  GET_USERS_LIST_ERROR: `${type}:${prefix}_GET_USERS_LIST_ERROR`,
  GET_REFERENCE_DATA_REQUEST: `${type}:${prefix}_GET_REFERENCE_DATA_REQUEST`,
  GET_REFERENCE_DATA_SUCCESS: `${type}:${prefix}_GET_REFERENCE_DATA_SUCCESS`,
  GET_REFERENCE_DATA_ERROR: `${type}:${prefix}_GET_REFERENCE_DATA_ERROR`,
  FILTER_USERS_LIST_REQUEST: `${type}:${prefix}_FILTER_USERS_LIST_REQUEST`,
  FILTER_USERS_LIST_SUCCESS: `${type}:${prefix}_FILTER_USERS_LIST_SUCCESS`,
  FILTER_USERS_LIST_CLEAR: `${type}:${prefix}_FILTER_USERS_LIST_CLEAR`,
  FILL_USER_DATA_FORM_REQUEST: `${type}:${prefix}_FILL_USER_DATA_FORM_REQUEST`,
  CLEAR_USER_DATA_FORM_REQUEST: `${type}:${prefix}_CLEAR_USER_DATA_FORM_REQUEST`,
};

